# Generated by Django 3.1.7 on 2021-04-02 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100)),
                ('event_datetime', models.DateTimeField()),
                ('event_add_datetime', models.DateTimeField(auto_now_add=True)),
                ('event_duration', models.IntegerField()),
                ('event_organizer', models.CharField(choices=[('CSI', 'Csi'), ('IEEE', 'Ieee'), ('ISTE', 'Iste'), ('ISA', 'Isa'), ('E_cell', 'E Cell'), ('CodeCell', 'Code Cell'), ('Cultural', 'Culturale'), ('Sports', 'Sportse'), ('Sort', 'Sorte'), ('Others', 'Others')], max_length=100)),
                ('event_details', models.FileField(blank=True, upload_to='uploads/')),
                ('event_description', models.TextField()),
                ('event_gformlink', models.URLField()),
            ],
        ),
    ]
