# Generated by Django 3.1.7 on 2021-04-03 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vesitEvents', '0002_auto_20210402_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='event_details',
            field=models.URLField(blank=True),
        ),
    ]
