# Generated by Django 3.1.7 on 2021-04-03 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vesitEvents', '0003_auto_20210403_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='event_status',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
