# Generated by Django 3.1.7 on 2021-04-03 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vesitEvents', '0004_events_event_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='event_organizer',
            field=models.CharField(choices=[('IIC', 'Iic'), ('Exam_Dept', 'Exam Dept'), ('CodeCell', 'Code Cell'), ('CSI', 'Csi'), ('IEEE', 'Ieee'), ('ISTE', 'Iste'), ('ISA', 'Isa'), ('E_cell', 'E Cell'), ('Cultural', 'Cultural Event'), ('Sports', 'Sports Event'), ('Sort', 'Sort Event'), ('Others', 'Others')], max_length=100),
        ),
    ]
