# Generated by Django 3.1.7 on 2021-04-03 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vesitEvents', '0005_auto_20210403_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='event_type',
            field=models.CharField(choices=[('Institute_level', 'Institute Level'), ('Department_level', 'Department Level'), ('Student_body', 'Student Body')], default='Student_body', max_length=100),
        ),
    ]
